-- 실시간 지하철 열차 위치를 저장하기 위한 테이블 생성
CREATE TABLE IF NOT EXISTS realtime_subway_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id VARCHAR(50),          -- subwayId: 지하철 호선 ID
    line_name VARCHAR(50),        -- subwayNm: 지하철 호선명
    station_id VARCHAR(50),       -- statnId: 지하철 역 ID
    station_name VARCHAR(100),    -- statnNm: 지하철 역명
    train_number VARCHAR(50),     -- trainNo: 열차 번호
    last_rec_date VARCHAR(20),    -- lastRecptnDt: 최종 수신 날짜
    last_rec_time VARCHAR(20),    -- recptnDt: 최종 수신 시간
    direction_type VARCHAR(10),   -- updnLine: 0=상행/내선, 1=하행/외선
    dest_station_id VARCHAR(50),  -- statnTid: 종착역 ID
    dest_station_name VARCHAR(100), -- statnTnm: 종착역명
    train_status VARCHAR(10),     -- trainSttus: 0=진입, 1=도착, 2=출발, 3=전전역출발 등
    is_express VARCHAR(10),       -- directAt: 1=급행, 0=아님, 7=특급
    is_last_train BOOLEAN,        -- lstcarAt: 막차 여부
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() -- 데이터 적재 시간
);

-- RLS(Row Level Security) 보안 설정 활성화
-- Supabase 대시보드의 'RLS disabled' 경고를 해결하고 데이터 접근 권한을 제어합니다.
ALTER TABLE realtime_subway_positions ENABLE ROW LEVEL SECURITY;

-- 1. 읽기 권한 허용 (모든 사용자)
-- 이 정책이 없으면 API를 통한 데이터 조회가 불가능할 수 있습니다.
CREATE POLICY "Enable read access for all users" ON realtime_subway_positions
    FOR SELECT USING (true);

-- 2. 쓰기 권한 허용 (모든 사용자)
-- 주의: 실제 서비스에서는 인증된 사용자만 쓰기가 가능하도록 제한해야 합니다.
-- 현재 프로젝트는 학습/테스트 용도이므로 편의를 위해 익명 키(anon key)로도 저장을 허용합니다.
CREATE POLICY "Enable insert access for all users" ON realtime_subway_positions
    FOR INSERT WITH CHECK (true);
