-- Create table for storing real-time subway train positions
CREATE TABLE IF NOT EXISTS realtime_subway_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id VARCHAR(50),          -- subwayId
    line_name VARCHAR(50),        -- subwayNm
    station_id VARCHAR(50),       -- statnId
    station_name VARCHAR(100),    -- statnNm
    train_number VARCHAR(50),     -- trainNo
    last_rec_date VARCHAR(20),    -- lastRecptnDt
    last_rec_time VARCHAR(20),    -- recptnDt
    direction_type VARCHAR(10),   -- updnLine: 0=Up/Inner, 1=Down/Outer
    dest_station_id VARCHAR(50),  -- statnTid
    dest_station_name VARCHAR(100), -- statnTnm
    train_status VARCHAR(10),     -- trainSttus: 0=Entry, 1=Arrival, 2=Departure...
    is_express VARCHAR(10),       -- directAt: 1=Express, 0=No, 7=Special
    is_last_train BOOLEAN,        -- lstcarAt
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Index for faster queries on specific lines or stations
CREATE INDEX idx_subway_line_id ON realtime_subway_positions(line_id);
CREATE INDEX idx_subway_train_number ON realtime_subway_positions(train_number);
CREATE INDEX idx_subway_created_at ON realtime_subway_positions(created_at);
